### ISSUE TITLE
What's the perms to run the commands?

### ISSUE THREAD

**Issue by AnifXD** [nxpinhum5326/TrollXD#2]
so when i try to run a command (im op) : /troll, and it says "u don't have a permission to run the commands", what's the solutions and the perms?,

sorry if my English bad

**Comment by nepinhum** [comment]
You can add permission named **trollxd.command.permission** from plugins like PurePerms etc. to yourself or to your tag. Or in plugin.yml
```
trollxd.command.permission:
   default: false
```
You can replace the "false" part with "op". 

And mine is certainly not that perfect 😸

**Comment by AnifXD** [comment]
Thx😃.
